### ISSUE TITLE
Error on startup on windows 10

### ISSUE THREAD

**Issue by GidyCazaus** [nitroshare/nitroshare-desktop#107]
Unable to Open

![nitroshare error](https://cloud.githubusercontent.com/assets/18597397/21008557/5ece5d06-bd29-11e6-8158-3396ac00b989.JPG)

**Comment by nathan-osman** [comment]
I've had one other user report this error and we were unable to figure out what was causing it. When NitroShare starts up, it listens for local connections from applications that use its API. In order to know which port to connect to (and ensure authorization), a secret token must be stored somewhere locally on the filesystem and its permissions set in such a way that it cannot be read by other users. This appears to be the block of code that is causing the error.

**Comment by tomkater68** [comment]
I also get this error, when nitroshare is installed with the installer from download page. If I checkout source from git repository and compile it with mingw32 compiler against Qt 5.8, the error doesn't appear. Don't know, if this helps.

**Comment by nathan-osman** [comment]
@tomkater68 did you also build QHttpEngine (one of NitroShare's dependencies)? Without QHttpEngine, the HTTP API won't work at all.

**Comment by tomkater68** [comment]
Hi Nathan,
you're right - I didn't link to QHttpEngine. After doing so, I also get the error. 
The error is caused by SetEntriesInAclW(), which returns errorcode 1332 ( ERROR_NONE_MAPPED   No mapping between account names and security IDs was done.). Changing

ea.Trustee.ptstrName = L"CREATOR OWNER";

to

ea.Trustee.ptstrName = "L"CURRENT_USER";";

in function QLocalFilePrivate::setPermission() seems to solve the problem.

**Comment by tomkater68** [comment]
Uuh, a misstake has slipped in -it should be

ea.Trustee.ptstrName = L"CURRENT_USER";

**Comment by nathan-osman** [comment]
Wow, I knew the problem had to be with the ACL code but I could never reproduce the problem to figure out what it was. Thanks so much! I'll get this fix into QHttpEngine immediately.

**Comment by bredoon** [comment]
So, closed. As to get rid of the error message?

**Comment by nathan-osman** [comment]
It's closed because the underlying issue has been fixed but the error message will not disappear until the next release.
