### ISSUE TITLE
Urgent update to be able to correct the errors in the first translation into Spanish.

### ISSUE THREAD

**Issue by jgjimenez** [nitroshare/nitroshare-desktop#108]
![seleccion_001](https://cloud.githubusercontent.com/assets/1020119/21020852/812ef27a-bd4c-11e6-9a1a-e5f9a33917ff.png)
As you can see is a translation in the style of tarzan. NitroShare is very good for keeping that old translation.

**Comment by mateosalta** [comment]
Do you have corrections for the translation Tarzan did? What errors need to be fixed, can you be more specific, I'm not sure what you are trying to say.

**Comment by nathan-osman** [comment]
The problem is that the Spanish translation included in the latest _stable_ release is quite poor. A patch was accepted that fixes the errors but there has not been a release yet.

The repository has another branch (redesign) that contains a bunch of new commits for the next version. As soon as this is usable, I will merge it into master and we'll get the next release out the door. 

Unfortunately, due to the large amount of work required to issue a release, I won't be releasing anything until the new version is ready for testing. That being said, the daily builds from here will have the new translation: https://ci.quickmediasolutions.com

**Comment by jgjimenez** [comment]
OK I figure I'll make the changes locally while an improved version comes out
