### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by insign** [nitroshare/nitroshare-desktop#234]
Sorry to ask, mainly if already asked (I searched).

But the lastest release was two years ago. And there is many open issues and some PR.

I understand that this is open for contributions, but there is a leader?

**Comment by x9sim9** [comment]
I think I read somewhere that the author was working on a new version with alot more features, but I got the impression that it may be more than they bargained with and so rather than continuing to maintain the old version they are focusing purely on a new version. For what nitroshare is it just needs some tweaks and polish to its current system, and explorer integration which could be done fairly easily.

I am not a C++ developer but I might have a look at some of the issues and feature requests that I would like. Such as pausing transfers and having transfers run sequentially rather than simultaneously, but time is always the issue. Are there any devs on here that would be willing to contribute towards a new version?

**Comment by jeffli678** [comment]
I also with to contribute but I am not good at C++. How about I port it to Python?

**Comment by nathan-osman** [comment]
There are a _lot_ of new features in the master branch since the latest stable release. These include an expanded API, the ability to send links, the return of shareboxes, and support for [native messaging](https://developer.chrome.com/apps/nativeMessaging).

Unfortunately, I have become very busy and have had very little free time to continue finishing up the next release and I was halfway through updating the build system when this happened. 😐 

I'm hoping that changes in the new year.

**Comment by insign** [comment]
Why not share your code as alpha and with hope some people can help you?

If already done, maybe a guideline for contribution. I can't help since I
work only with web technologies.

Em sáb, 14 de dez de 2019 20:13, Nathan Osman <notifications@github.com>
escreveu:

**Comment by nathan-osman** [comment]
> Why not share your code as alpha and with hope some people can help you?

I have — it's in the master branch. The application will still build from source; it's the packaging scripts that are currently being worked on.

**Comment by dmyurych** [comment]
Hi Nathan, it's been over a year with no updates.

It there some way we can support you financially to continue development for those of us that either can't code or don't have the time or inclination to get involved in the development? Perhaps one of these or other options for you to get paid:
  https://www.patreon.com/
  https://flattr.com/
  https://opencollective.com/
  
I use NitroShare to transfer files from my Android phone to my Mac. It's great as it is the best solution I've found and it's a bonus that it's also open source. However I have a (an already reported) problem when transferring the other way. It sounds like you are totally revamping the program for the next version. Perhaps consider continuing to fix bugs on the current stable version while you work on the this. I would even support a bug bounty to actually get the fix that I need.

Many of us definitely appreciate your efforts and some of us would like to see you rewarded in some way.

**Comment by nathan-osman** [comment]
Sadly, it isn't so much an issue of cost as it is time. With COVID-19 hitting, I've been extremely busy with work and other things that have come up because of the pandemic.

I have made a number of bug fixes to the QHttpEngine and QMdnsEngine libraries which form an essential part of the application. However, the installers on the website don't include the newest versions of these libraries, so my first step would be to release new installers that include them. I can't make any promises, but if I have time over the holidays, I will look into doing that.

The new version in development (v0.4) is quite complex — the application has been split into several smaller components and there is a new plugin system. It offers a number of new features, such as sending links, shareboxes, a setup wizard, etc. Unfortunately, it is only partially complete. The core features are there but they still need a bit of polishing. I'm still hoping to get to this at some point in the future.
