### ISSUE TITLE
Cannot build under ubuntu 14.04?

### ISSUE THREAD

**Issue by zycbobby** [nitroshare/nitroshare-desktop#31]
I am using Ubuntu 14.04, the desktop env is gnome-3.10
 here is what I have done

```bash
sudo apt-get install build-essential qtbase5-dev libqt5svg5 libgtk2.0-dev libappindicator-dev libnotify-dev
cd nitroshare-desktop
qmake
make
```

but it ends up with 

```
cd src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/zuo/Code/nitroshare-desktop/src/src.pro -o Makefile ) && make -f Makefile 
sh: 1: rpm: not found
Project ERROR: Unknown module(s) in QT: svg
make: *** [src-make_first] Error 3
```

I have checked the source code, I think I dont need to use rpm right?

**Comment by nathan-osman** [comment]
You can ignore the `rpm: not found` error - NitroShare is just checking to see if the RPM command is available (so that it knows whether it's being built on a Debian or Redhat-based distro).

The real error is caused by qmake being unable to locate the Qt SVG module. The problem is that you are missing the `-dev` package. You installed `libqt5svg5`, but the package you need is `libqt5svg5-dev`. The build should succeed after installing that package. If not, feel free to reopen this issue.

**Comment by zycbobby** [comment]
I have checked it. It can successfully built.

I want to know one more thing: does it work on gnome-3.10? I cannot see the UI where it run 

```bash
 ./out/install/nitroshare
```

**Comment by nathan-osman** [comment]
Yes, it works on Gnome 3, but you will need to install this extension:

https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by zycbobby** [comment]
Thank you sooooooooo much, it works.
